/**
 * 3D Hand & Finger Calibration Map for KeyVibe Touch Typing Studio
 * Maps physical keyboard keys to assigned fingers and 3D offset micro-adjustments.
 *
 * Generated by KeyVibe 3D Calibrator Studio.
 */

export const KEY_CALIBRATION = {
  // Row 0: Number Row
  Backquote: { finger: 'LP', offsetX: 0, offsetZ: 0, offsetY: 0 },
  Digit1: { finger: 'LP', offsetX: 20.13, offsetZ: 8.77, offsetY: -16 },
  Digit2: { finger: 'LR', offsetX: 12.11, offsetZ: 4.09, offsetY: 0 },
  Digit3: { finger: 'LM', offsetX: 8.1, offsetZ: 4.76, offsetY: 0 },
  Digit4: { finger: 'LI', offsetX: 4.09, offsetZ: 6.77, offsetY: 0 },
  Digit5: { finger: 'LI', offsetX: 10.11, offsetZ: -0.45, offsetY: 0 },
  Digit6: { finger: 'RI', offsetX: 0.75, offsetZ: -5.26, offsetY: 0 },
  Digit7: { finger: 'RI', offsetX: -1.25, offsetZ: -2.59, offsetY: 0 },
  Digit8: { finger: 'RM', offsetX: -3.96, offsetZ: 3.43, offsetY: 0 },
  Digit9: { finger: 'RR', offsetX: -6, offsetZ: 2.76, offsetY: 0 },
  Digit0: { finger: 'RP', offsetX: -7.27, offsetZ: 1.42, offsetY: 0.38 },
  Minus: { finger: 'RP', offsetX: -5.93, offsetZ: 13.45, offsetY: 0.04 },
  Equal: { finger: 'RP', offsetX: 0, offsetZ: 0, offsetY: 0 },
  Backspace: { finger: 'RP', offsetX: -17.96, offsetZ: 14.79, offsetY: -50 },

  // Row 1: Top Row
  Tab: { finger: 'LP', offsetX: 0, offsetZ: 0, offsetY: 0 },
  KeyQ: { finger: 'LP', offsetX: 14.12, offsetZ: -7.27, offsetY: 0 },
  KeyW: { finger: 'LR', offsetX: 4.09, offsetZ: 0.08, offsetY: 0 },
  KeyE: { finger: 'LM', offsetX: 4.76, offsetZ: 0.75, offsetY: 0 },
  KeyR: { finger: 'LI', offsetX: 1.42, offsetZ: 2.76, offsetY: 0 },
  KeyT: { finger: 'LI', offsetX: 6.1, offsetZ: -1.25, offsetY: 0 },
  KeyY: { finger: 'RI', offsetX: -7.27, offsetZ: -7.27, offsetY: 0 },
  KeyU: { finger: 'RI', offsetX: -1.22, offsetZ: -0.71, offsetY: 0 },
  KeyI: { finger: 'RM', offsetX: -1.92, offsetZ: 0.61, offsetY: 0 },
  KeyO: { finger: 'RR', offsetX: 0, offsetZ: 0.26, offsetY: 0 },
  KeyP: { finger: 'RP', offsetX: -4.04, offsetZ: -7.36, offsetY: 0 },
  BracketLeft: { finger: 'RP', offsetX: -5.93, offsetZ: 0, offsetY: 0 },
  BracketRight: { finger: 'RP', offsetX: 0, offsetZ: 0, offsetY: 0 },
  Backslash: { finger: 'RP', offsetX: 0, offsetZ: 0, offsetY: 0 },

  // Row 2: Home Row
  CapsLock: { finger: 'LP', offsetX: 0, offsetZ: 0, offsetY: 0 },
  KeyA: { finger: 'LP', offsetX: 0.44, offsetZ: -1.92, offsetY: 0 },
  KeyS: { finger: 'LR', offsetX: -2.9, offsetZ: -1.35, offsetY: 0 },
  KeyD: { finger: 'LM', offsetX: 2.25, offsetZ: -0.87, offsetY: 0 },
  KeyF: { finger: 'LI', offsetX: 0.69, offsetZ: 0.08, offsetY: 0 },
  KeyG: { finger: 'LI', offsetX: 8.1, offsetZ: -5.26, offsetY: 0 },
  KeyH: { finger: 'RI', offsetX: -7.27, offsetZ: -5.26, offsetY: 0 },
  KeyJ: { finger: 'RI', offsetX: -0.31, offsetZ: -0.4, offsetY: 0 },
  KeyK: { finger: 'RM', offsetX: 0.75, offsetZ: -0.42, offsetY: 0 },
  KeyL: { finger: 'RR', offsetX: 4.53, offsetZ: -1.57, offsetY: 0 },
  Semicolon: { finger: 'RP', offsetX: 5.02, offsetZ: -3.74, offsetY: -7.64 },
  Quote: { finger: 'RP', offsetX: 2.76, offsetZ: -4.59, offsetY: 0 },
  Enter: { finger: 'RP', offsetX: 0, offsetZ: 0, offsetY: 0 },

  // Row 3: Bottom Row
  ShiftLeft: { finger: 'LP', offsetX: 0, offsetZ: 0, offsetY: 0 },
  KeyZ: { finger: 'LP', offsetX: -7.94, offsetZ: 0.08, offsetY: 0 },
  KeyX: { finger: 'LR', offsetX: -4.1, offsetZ: -2.95, offsetY: 0 },
  KeyC: { finger: 'LM', offsetX: 2.09, offsetZ: 0.08, offsetY: 0 },
  KeyV: { finger: 'LI', offsetX: 2.09, offsetZ: -1.25, offsetY: 0 },
  KeyB: { finger: 'LI', offsetX: 13.45, offsetZ: -9.27, offsetY: 0 },
  KeyN: { finger: 'RI', offsetX: -5.93, offsetZ: -3.26, offsetY: 0 },
  KeyM: { finger: 'RI', offsetX: 4.09, offsetZ: 0.08, offsetY: 0.38 },
  Comma: { finger: 'RM', offsetX: 7.44, offsetZ: 2.09, offsetY: 0 },
  Period: { finger: 'RR', offsetX: 10.11, offsetZ: -1.25, offsetY: 0 },
  Slash: { finger: 'RP', offsetX: 12.11, offsetZ: -5.93, offsetY: 0 },
  ShiftRight: { finger: 'RP', offsetX: 9.44, offsetZ: -9.94, offsetY: 0 },

  // Row 4: Space Row
  ControlLeft: { finger: 'LP', offsetX: -17.96, offsetZ: -10.61, offsetY: 0 },
  MetaLeft: { finger: 'LP', offsetX: 0, offsetZ: 0, offsetY: 0 },
  AltLeft: { finger: 'LT', offsetX: 0, offsetZ: 0, offsetY: 0 },
  Space: { finger: 'RT', offsetX: 0, offsetZ: 0, offsetY: 0 },
  AltRight: { finger: 'RT', offsetX: 0, offsetZ: 0, offsetY: 0 },
  MetaRight: { finger: 'RP', offsetX: 0, offsetZ: 0, offsetY: 0 },
  ControlRight: { finger: 'RP', offsetX: 18.13, offsetZ: -15.96, offsetY: 0 },

};

export const DEFAULT_HAND_TRANSFORM = {
  scale: 3.3,
  posX: -11.28,
  posY: -30.03,
  posZ: -49.37,
  spacing: -30.37,
  yaw: -33.4,
  pitch: -40.6,
  roll: -28.6,
};

export const DEFAULT_FINGER_POSTURE = {
  masterCurl: 2.16,
  reachStretch: 1.35,
  masterSplay: 0.27,
  curlIndex: 0.39,
  curlMiddle: 0.54,
  curlRing: 0.44,
  curlPinky: 0.25,
  curlThumb: 0.26,
  splayIndex: -0.025,
  splayPinky: -0.08,
  splayThumb: -0.02,
};

/**
 * Get active calibration for a key (merging stored overrides over defaults)
 * @param {string} keyId
 * @returns {{ finger: string, offsetX: number, offsetZ: number, offsetY: number }}
 */
export function getKeyCalibration(keyId) {
  let custom = null;
  try {
    const raw = localStorage.getItem('keyvibe_finger_calibration');
    if (raw) {
      const map = JSON.parse(raw);
      if (map && map[keyId]) custom = map[keyId];
    }
  } catch (_) { }

  const base = KEY_CALIBRATION[keyId] || { finger: 'LI', offsetX: 0, offsetZ: 0, offsetY: 0 };
  return custom ? { ...base, ...custom } : base;
}

/**
 * Get all active calibrations
 * @returns {Record<string, { finger: string, offsetX: number, offsetZ: number, offsetY: number }>}
 */
export function getAllCalibrations() {
  const result = { ...KEY_CALIBRATION };
  try {
    const raw = localStorage.getItem('keyvibe_finger_calibration');
    if (raw) {
      const map = JSON.parse(raw);
      if (map) {
        Object.keys(map).forEach(k => {
          result[k] = { ...result[k], ...map[k] };
        });
      }
    }
  } catch (_) { }
  return result;
}

/**
 * Get global hand transform (scale, move position, rotation)
 * @returns {{ scale: number, posX: number, posY: number, posZ: number, spacing: number, yaw: number, pitch: number, roll: number }}
 */
export function getGlobalHandCalibration() {
  try {
    const raw = localStorage.getItem('keyvibe_hand_global_calibration');
    if (raw) {
      const parsed = JSON.parse(raw);
      if (parsed) return { ...DEFAULT_HAND_TRANSFORM, ...parsed };
    }
  } catch (_) { }
  return { ...DEFAULT_HAND_TRANSFORM };
}

/**
 * Get finger posture calibration (resting curls, stretch sensitivity, lateral splays)
 * @returns {{ masterCurl: number, reachStretch: number, masterSplay: number, curlIndex: number, curlMiddle: number, curlRing: number, curlPinky: number, curlThumb: number, splayIndex: number, splayPinky: number, splayThumb: number }}
 */
export function getFingerPostureCalibration() {
  try {
    const raw = localStorage.getItem('keyvibe_finger_posture');
    if (raw) {
      const parsed = JSON.parse(raw);
      if (parsed) return { ...DEFAULT_FINGER_POSTURE, ...parsed };
    }
  } catch (_) { }
  return { ...DEFAULT_FINGER_POSTURE };
}
